### ISSUE TITLE
Rethinking Structure regarding Trade Class 

### ISSUE THREAD

**Issue by ik8472** [hhu-propra2/abschlussprojekt-bugrog-morgoth-ush-parse#29]
Maybe another Class Structure is more sensible after all. Consider the following Use Case: A User sends a Trade request to a Supplier, this Supplier however does not react to the request - leading the User to request the same Item from another Supplier who reacts in time. After the User already has the Item the, now useless, request to the other Supplier still stands without a possibility for the User to revoke the request. 
So maybe a Class Offer would be more sensible. This Offer could be send to the Supplier by the User and also be revoked by the User. Upon accepting the Offer (by the Supplier) a new Objekt of Class Contract could be formed. Viewing the relationship this way would also be the legally correct way.

**Comment by brokelyn** [comment]
We could revert the state of the trade with a button. The button is visible to the user when he send a trade request. I don't think we need an extension of our current model for this case, especially because this is a rare edge case.

**Comment by ik8472** [comment]
While i agree that this can also be implemented in our current implementation (or planning thereof) this certainly is neither edge nor rare ... If you really need an Item trying several Suppliers seems a perfectly reasonable idea, especially since you never know when and if someone will accept your request (Or do you, if you really want something only bid on one and only one auction on eBay?). Therefore it definitely should be possible to revoke requests.

**Comment by claussmann** [comment]
If i woul potentially want to buy a __jackhammer__ on an EBay-auction, i would not participate on more than one auction at a time as long as i would be at winning that auction... Well i don't want two of them...
__Whatever__: A user can cancel a request/trade whenever he wants with a button. In case he really got 2 jackhammers he can simply write back to the lender that he already got one. __We will need a posibility to chat with lender and borrower anyway__ because they have to talk about a time to pick up the item...?
And if the lender just marks the item as *returned*  when the borrower doesn't need it, we can solve the problem very simple (but not that elegant)

Could this be a solution?

**Comment by tnfru** [comment]
done - trade is replaced by offer and contract
